apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: inference-graph
spec:
  name: inference-graph-spec
  replicas: 1
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: detection:1.0
          name: detection
        - image: translation:1.0
          name: translation
#        - image: router:1.0
#          name: router
        - image: intent:1.0
          name: intent
        - image: entity:1.0
          name: entity
        - image: summary:1.0
          name: summary
        - image: combiner:1.0
          name: combiner
    graph:
      name: combiner
      type: COMBINER
      children:
        - name: detection
          type: MODEL
          children:
            - name: translation
              type: MODEL
              children:
                - name: intent
                  type: MODEL
                - name: summary
                  type: MODEL
                - name: entity
                  type: MODEL
    name: seldon-inference-graph